# generated by fastapi-codegen:
#   filename:  api-definition/logoservice.yaml
#   timestamp: 2024-06-20T18:48:54+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field
from typing import List


class Action(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    description: Optional[str] = None
    executions: Optional[List[Execution]] = None

class Execution(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    status: Optional[bool] = None
    triggeredAt: Optional[datetime] = None
    finishedAt: Optional[datetime] = None